### ISSUE TITLE
添加bugsnag

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/haxibiao#1]
这个项目的异常主要让彭聪来监控吧

**Comment by ivanzhang2** [comment]
彭聪：
1. 确保哈希表网站的　bugsnag 在线上还能正常工作
2. 确保ainicheng等旗下网站也都在bugsnag的异常跟踪下，所有项目代码相同，用ainicheng一个key跟踪就够了

**Comment by caizhigang1997** [comment]
这个先关了
