### ISSUE TITLE
编辑专题需要改进的地方

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/haxibiao#14]
１．　选择其他管理员的时候，要选择当前用户关注的用户列表
２．　选择至少１３个官方专题，并为勾上ａｐｐ，并上传符合APP ＵＩ风格的简易LOGO.
３．　检查graphql 是否提取了１３个带app图标的专题，

**Comment by caizhigang1997** [comment]
选择其他管理员的时候，要选择当前用户关注的用户列表。如果用户没有关注任何用户就默认为空。

**Comment by caizhigang1997** [comment]
1.已经修复

**Comment by ivanzhang2** [comment]
1 2 3 都已经上线
