### ISSUE TITLE
haxibiao.com的seo配置管理

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/haxibiao#4]
哈希表公司网目前的百度索引量：6415

其中有很多抓取的文章百度也收录了，说明哪些内容的格式和样式是可以被收录的，这里彭聪帮曾倩完成网站seo配置功能，明天起，我们希望日报看到哈希表网站的运营状况。

如果haxibiao.com早点突破百度权重1，我们就有一个成功的权重1，方便带领其他的网站一起突破。

**Comment by zixin** [comment]
已完成，明天可以出运营报表。
