### ISSUE TITLE
文章评论区的回复在后台的消息通知里看不到，用户无法及时查看回复消息

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#52]
如图,消息通知里只能看到自己文章被他人评论的提示，无法看到自己去其他文章下方的评论被回复的内容，
可以设置一个回复楼层评论 自动艾特层主的功能，方便用户及时查看消息参与评论区的交流互动。
![image.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/ebd886b1-9b4e-4511-b8e3-14a2598082e7)

![image.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/6e79a247-2365-4b8c-9920-3e5f69d241e1)

**Comment by yangliu9494** [comment]
![QQ图片20180628105957.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/136806c5-c786-4bee-ba97-782e0cda0a3b)
![QQ图片20180628110021.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/a4797ad2-b06f-4f69-89cc-5535c3e36de7)

**Comment by caizhigang1997** [comment]
已经解决 @yangliu9494

**Comment by yangliu9494** [comment]
等实现回复楼层自动艾特功能

**Comment by caizhigang1997** [comment]
该功能前端已经实现

**Comment by yangliu9494** [comment]
已完成
