### ISSUE TITLE
投稿过的文章已经删除却上了首页轮播图

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#56]
![UE76%3GCGOPJW6EXZLN]LBN.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/0c0fd114-e354-401e-8af8-bf225a9e6511)

**Comment by yangliu9494** [comment]
谷歌浏览器无法登陆。输入账号密码后点击登陆没有反应。
 ![[3LIDB)FL8KE4ZSX2LP)WIF.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/c7fdec24-9083-4d0e-99ec-f4e669cb858d)


用户点击首页轮播图上删除的文章 提示网页不存在 。
![9]LZ884S[2%FA%(~WDHC[)1.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/2c4a500e-3005-4999-b694-f860903a3b02)

编辑身份任然可以查看到已经删除的文章。

**Comment by caizhigang1997** [comment]
已经解决

**Comment by yangliu9494** [comment]
谷歌浏览器可以登录了，但是编辑身份后台手动上的轮播图删除后还是会出现在轮播图。

**Comment by yangliu9494** [comment]
测试过已解决，编辑身份删除置顶轮播图文章需在后台把置顶下了就OK了。
