### ISSUE TITLE
网页消息提示已经点开查看了，还是会有小气泡提示。

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#58]
![4F7S_K_E0%MEBH5LZHTOOFP.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/faf5f3b4-d6de-4dff-b3fb-6c539349332a)

**Comment by caizhigang1997** [comment]
已经解决

**Comment by yangliu9494** [comment]
小气泡需要刷新网页才会消失。后期的话能不能改进为用户点击过小气泡提示就消失无需刷新网页。
