### ISSUE TITLE
网站我的主页点击关注的专题后再点编辑无反应。

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#59]
如图，进入我的主页，点击右边的关注的专题、关注的文集和文章。再点编辑无反应，关注人数显示空白、页面数据错误。

![X5YFIK7TVBGXVIK6VU$WDUN.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/ba423935-3ffb-4ee8-a40b-082145b73957)

![3D[SJ)8(OXM}N)JV}(EBQ(A.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/7f831009-7f5f-4ae8-9d0b-f12c872e2476)

**Comment by leikun222** [comment]
bug已修复

**Comment by yangliu9494** [comment]
如图，点击我关注的专题，下面的关注栏排版位置不整齐。       另外头像旁边的关注数量那里一直都显示空白。
![5 _cg f_jv 3ryn v9nnnru](https://user-images.githubusercontent.com/40386628/42569121-0f856cde-8542-11e8-9e39-c02d44cab659.png)

**Comment by leikun222** [comment]
问题1.已解决.
问题2.需要后端帮忙.

**Comment by yangliu9494** [comment]
已经和老王说过这个问题。

**Comment by yangliu9494** [comment]
已检查，已正常
![C[ZOPOSH](1LQ4TQ)~{K{Z8.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/c518c822-aac9-4cb4-882f-ae0ac2ac16ff)
