### ISSUE TITLE
搜索用户后点击关注，跳转页面数据不对，用户关注数量不对。

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#60]
如图，搜索用户后点击关注，跳转数据不对，跳转的是编辑面板页面，用户关注数量显示也不对，显示的关注包括了专题数量。
![`F215QR`M4[Y`AQ_LKIPE6O.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/30368553-c3b1-45de-8805-92b476b9891c)

**Comment by XiaoXinMing** [comment]
2018年07月19日11:46:19

已经修复：

![2018-07-19 11-46-42屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/f475bf9a-8e19-4999-a36c-df0d4842148f)

**Comment by yangliu9494** [comment]
跳转详情数据对了。搜索页面用户的关注数量和实际数量还是不对，如图：
![wp85 o 6p9v9mq erenxo](https://user-images.githubusercontent.com/40386628/42920721-c3f1650c-8b4a-11e8-8747-a08fc2f15fe0.png)


实际详情页是18关注数：

![kotksa 9crmgkwt d wwp](https://user-images.githubusercontent.com/40386628/42920725-c7398230-8b4a-11e8-82bd-f020191ab8ed.png)

**Comment by XiaoXinMing** [comment]
前面没办法看到图。

已经修复 ，麻烦下次把"爱你城"的BUG 放到"爱你城"仓库下

**Comment by yangliu9494** [comment]
OK已检查修复。
