### ISSUE TITLE
热门专题下拉到底的加载条摆放布局有问题

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#61]
如图
![TITI6FA[28Q5`A0E397R06F.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/38ea0242-7ad1-4b5c-b881-be12f4a6ab28)

**Comment by yangliu9494** [comment]
应该放在最后一行

**Comment by XiaoXinMing** [comment]
这个需求的图片 无法看到  请重新上传一遍

**Comment by yangliu9494** [comment]
检查已改成翻页浏览。已正常。
![YJ8ADK99HGF~WQ{UZ4@31R0.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/9834fb63-6d83-48a4-b4c7-5b54869e72ec)
