### ISSUE TITLE
编辑面板管理文章旁的搜索栏点击无反应。

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#62]
如图 
![}ZT0Y`Z4{V_KLS0){7B$PDB.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/c69306ae-5e22-4a0a-92b3-3116a04ff6dc)

**Comment by XiaoXinMing** [comment]
已经修复完成：

可以通过"回车键"或点击"搜索按钮"触发
![2018-07-19 10-41-39屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/f8336767-cddb-4624-9675-4a89e87f4361)

**Comment by yangliu9494** [comment]
已修复
![7n 829ij rc2w n 3p k 3a](https://user-images.githubusercontent.com/40386628/42920495-76f5f96c-8b49-11e8-8b33-a5d71d8978fe.jpg)
