### ISSUE TITLE
管理中心添加一个置顶视频，在视频中心页面下方的推荐视频， 可以置顶我们的官方原创视频等。

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#65]
如图
![11HR`BGVV2YN1_$7(W0[CJP.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/1516d74e-f4f5-403e-b85e-0b09ae3934c3)

**Comment by XiaoXinMing** [comment]
这个需求的图片 看不到 麻烦重新上传演示一下。

**Comment by yangliu9494** [comment]
如图，www.ainicheng.com/admin  编辑后台这里添加
![80dr e hk5o 5yf rv s](https://user-images.githubusercontent.com/40386628/42923710-8ac86de8-8b59-11e8-973b-192af6b7cdaf.png)

**Comment by yangliu9494** [comment]
在视频中心下拉到底的推荐视频这里，让我们编辑可以手动置顶单个视频。
![y awnw4 nguywx 4vxs t](https://user-images.githubusercontent.com/40386628/42923753-cb5bac6c-8b59-11e8-9af7-52f96c83d64b.jpg)

**Comment by XiaoXinMing** [comment]
已经添加了置顶功能：
![2018-07-24 11-33-55](https://user-images.githubusercontent.com/39290488/43115209-7964d0ca-8f35-11e8-9f64-787259755877.png)
视频置顶
![2018-07-24 11-34-23](https://user-images.githubusercontent.com/39290488/43115228-97a07d28-8f35-11e8-93ba-32e4a8f6ba43.png)

**Comment by yangliu9494** [comment]
已检查完成
