### ISSUE TITLE
文章详情页下面点开收入我的专题栏点击搜索无反应

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#67]
如图
![_FYPK{VC3`@E(QE9$@}%@3D.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/8c3e1f43-f9e3-470f-9669-9f21e17d801e)

**Comment by XiaoXinMing** [comment]
2018年07月19日13:36:47

已经修复完成：

可以通过"回车键"或点击"搜索按钮"触发
![2018-07-19 13-37-46屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/dd7a2d96-8567-4a07-b616-4eee906ae4a8)

**Comment by yangliu9494** [comment]
建议：在投稿搜索中可以出现非自己管理外的相关专题，如图，搜索dota2，下面的推荐专题建议可以按算法修改为dota2和dota2相关的专题，便于用户投稿。
![270pp6p pz8m_s 4580 b8](https://user-images.githubusercontent.com/40386628/42923984-d42ff810-8b5a-11e8-9a4b-f385ad5d1e64.png)

**Comment by XiaoXinMing** [comment]
正常

![2018-07-25 10-33-30屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/919612b2-48b9-493b-be81-8e2638b3948d)

**Comment by XiaoXinMing** [comment]
已经修复：
2018年07月25日14:19:21
精准匹配->模糊匹配

![2018-07-25 14-19-08屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/b7529856-9f3c-48ea-b17b-5ebd199036be)

**Comment by XiaoXinMing** [comment]
![2018-07-25 14-42-09屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/ea75580c-dc7f-4779-b7d0-2214d1103600)

**Comment by yangliu9494** [comment]
已完成
