### ISSUE TITLE
爱你城graphql需求(3)

### ISSUE THREAD

**Issue by wangyukun-hxb** [haxibiao/haxibiao#68]
### 1.文章body图片带上width、height属性
<img width="" height=""/>
因为在APP上渲染图片必须要指定宽高，但是不知道图片比例会造成渲染不正常。

### 2.评论body按数组格式返回
["string",{id:Int,name:string},"string","string",{id:Int,name:string}]

### 3.记录最近浏览过的专题，并带上最近的更新数量。
最后浏览过的永远排在第一；可单个删除记录
![image.png](https://images.zenhubusercontent.com/5ab452a24b5806bc2bcc0bde/8973c1eb-44a4-41fe-82a6-bc12d8f25280)

**Comment by caizhigang1997** [comment]
<b>1.文章体中的图片都加入了宽高属性。</b>
<b>2.评论功能上线以后返回的格式如下：</b>
```
{
  "data": {
    "addComment": {
      "id": 409,
      "body": "[{\"type\":\"user\",\"id\":\"1\",\"name\":\"江湖小郎中\"},\" test gewi\"]",
      "user": {
        "id": 1,
        "name": "江湖小郎中",
        "avatar": "http://l.ainicheng.com/storage/avatar/1.jpg"
      },
      "time_ago": "1 秒 前"
    }
  }
}
```
*<b>大体上的需求与我们之前沟通的一致，只是多加了一个type。有#专题这个需求(不多现在还没开始做，先占个坑)</b>*
<b>3.需求已经明白</b>

*上线了会继续回复*😆

**Comment by wangyukun-hxb** [comment]
好的🤓

**Comment by caizhigang1997** [comment]
```php
#最近逛过的专题
query visitCategoryQuery($offset:Int,$limit:Int){
    visits(offset: $offset,limit: $limit,type:CATEGORY) {
        id
        visited {
            id
            title
             logo
            dynamic_msg
        }
    }
}
#删除浏览记录
mutation deleteVisitMutation($id: Int!) {
    deleteVisit(id: $id) {
        id
    }
}
```
