### ISSUE TITLE
首页推荐视频一栏的更多点击跳转页面是管理视频列表页面，请修改为视频入口

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/haxibiao#69]
如图
![W~~6B)Z$I{4QHR1OGBE@KGH.jpg](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/d8ce6013-1fe9-45da-9d56-311e9061e76e)
跳转后：
![J`WR6S8@ZQ7E}~T}KHIYN3N.jpg](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/7e192a99-4131-4a2b-a5ae-cca0a40b4324)

**Comment by gaoxuan-haxibiao** [comment]
好了

**Comment by yangliu9494** [comment]
已检查完成。
